export const example = {
  restaurantID: `${Date.now()}`,
  restaurant: "restaurant",
  restaurantImage: "restaurantImage",
  location: location,
  categoriesInRestaurant: "selectedValues",
  dishes: [
    {
      id: `${Date.now()}`,
      title: "",
      category: "",
      calories: "",
      price: "",
      imageAsset: null,
      qty: 1,
    },
    {
      id: `${Date.now()}`,
      title: "",
      category: "",
      calories: "",
      price: "",
      imageAsset: null,
      qty: 1,
    },
    {
      id: `${Date.now()}`,
      title: "",
      category: "",
      calories: "",
      price: "",
      imageAsset: null,
      qty: 1,
    },
    {
      id: `${Date.now()}`,
      title: "",
      category: "",
      calories: "",
      price: "",
      imageAsset: null,
      qty: 1,
    },
  ],
};
